Implementation of database functions for tags & scans. RPC routing included.
LarsDepuydt/peno-entrepreneurship-3d-oclusion pull request #5
Opened 2023-03-06 09:50 UTC by DagMalstaf

Created functions for tags and scans. 
Request and Response routing also implemented
Tags:
- AddTag()
- DeleteTag()
- GetAllTags()
- GetTagByID()
- GetAllTagsByType()

Scans:
- AddScan()
- DeleteScan()
- GetAllScans()
- GetScanByID()
- GetScanByDate()

2023-03-06 14:09 UTC, LarsDepuydt requested changes
Op het eerste zicht ziet het er wel uit, nog 2 belangrijke dingen:
- GET requests returnen de data die opgevraagd wordt, geen message
- message: 'done' is super nietszeggend, ik zou liever iets zien van `successfully {action} {type} with {id}`

2023-03-06 14:09 UTC, LarsDepuydt commented on backend/cmd/scans/scans.go
> +func GetScanByDate(req *connect.Request[threedoclusionv1.GetScanByDateRequest]) (*connect.Response[threedoclusionv1.GetScanByDateResponse], error) {
hzo by date? Bedoel je op een bepaalde dag ofzo? Dan werk je beter met een start en end date (in iso string formaat) (flexibeler en cleaner)

2023-03-06 14:09 UTC, LarsDepuydt commented on backend/cmd/scans/scans.go
> -	res.Header().Set("Scan-Version", "v1")
Ik zou deze header overal nog durven toevoegen, moesten we ooit een migration doen, dan is het cleaner

2023-03-06 14:09 UTC, LarsDepuydt commented on backend/cmd/tags/tags.go
> +func AddTag(req *connect.Request[threedoclusionv1.AddTagRequest]) (*connect.Response[threedoclusionv1.AddTagResponse], error) {
Ik zou een tag ook nog een `color` geven

2023-03-06 14:09 UTC, LarsDepuydt commented on backend/cmd/tags/tags.go
> +		Message: "done",
idem

2023-03-06 14:09 UTC, LarsDepuydt commented on backend/cmd/tags/tags.go
> +		Message: "done",
idem

2023-03-06 14:09 UTC, LarsDepuydt commented on backend/cmd/tags/tags.go
> +	_, error = database.Exec(statement, req.Msg.TableName)
idem

2023-03-06 14:09 UTC, LarsDepuydt commented on backend/cmd/tags/tags.go
> +		Message: "done",
idem

2023-03-06 14:09 UTC, LarsDepuydt commented on backend/cmd/tags/tags.go
> +		Message: "done",
idem

2023-03-06 14:09 UTC, LarsDepuydt commented on backend/cmd/tags/tags.go
> +	fmt.Println("Got the tag by type succesfully")
can be multiple tags right?

2023-03-06 14:09 UTC, LarsDepuydt commented on proto/threedoclusion/v1/service.proto
> +}
een response van een get zou de data moeten zijn die je wou opvragen, niet gewoon een message. Idem voor alle andere GET requests

2023-03-06 14:30 UTC, DagMalstaf commented on backend/cmd/scans/scans.go
> +	_, error = database.Exec(statement, req.Msg.TableName)
ik had dit zo geïmplementeerd voor als we eventueel ergens willen dubbelchecken of de juiste data wordt opgevraagd. Door te checken of de functie effectief uit de juiste tabel haalt. Dit was vooral om de routing robuster te maken... Maar misschien is dat overbodig?

2023-03-06 14:30 UTC, DagMalstaf commented on backend/cmd/scans/scans.go
> +	_, error = database.Exec(statement, req.Msg.TableName)
+ dan is er niet echt een message nodig voor Request van deze route? Maakt dat uit?

2023-03-06 14:30 UTC, DagMalstaf commented on backend/cmd/tags/tags.go
> +	_, error = database.Exec(statement, req.Msg.TableName)
ik had dit zo geïmplementeerd voor als we eventueel ergens willen dubbelchecken of de juiste data wordt opgevraagd. Door te checken of de functie effectief uit de juiste tabel haalt. Dit was vooral om de routing robuster te maken... Maar misschien is dat overbodig?

2023-03-06 14:48 UTC, DagMalstaf commented on backend/cmd/scans/scans.go
> -	res.Header().Set("Scan-Version", "v1")
moet dat in elke functie staan dan?

2023-03-06 14:49 UTC, DagMalstaf commented on backend/cmd/tags/tags.go
> +	fmt.Println("Got the tag by type succesfully")
yes

2023-03-06 14:49 UTC, DagMalstaf commented on proto/threedoclusion/v1/service.proto
> +}
helemaal over het hoofdgezoen om de waarde van de database ook effectief terug te geven! my bad, ik fiks het nu!

2023-03-06 15:11 UTC, DagMalstaf commented on backend/cmd/tags/tags.go
> +func AddTag(req *connect.Request[threedoclusionv1.AddTagRequest]) (*connect.Response[threedoclusionv1.AddTagResponse], error) {
is voor sprint 2

2023-03-07 14:16 UTC, LarsDepuydt approved these changes

2023-03-07 14:16 UTC, LarsDepuydt commented on backend/cmd/scans/scans.go
> +		Message:   "Returned all scans",
dit niet

2023-03-07 14:16 UTC, LarsDepuydt commented on database/migrations/database.up.sql
> -    id SERIAL PRIMARY KEY,
auto increment

2023-03-07 14:27 UTC, merged